//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEZPortalClock
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("FEZPortalClock.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static System.Drawing.Bitmap GetBitmap(Resources.BitmapResources id)
        {
            return ((System.Drawing.Bitmap)(ResourceManager.GetObject(((short)(id)))));
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            LED2B = -30107,
            LED2G = -30104,
            LED2R = -30091,
            LED7B = -28635,
            LED7R = -28619,
            LED7G = -28454,
            LEDG = -14322,
            LED3B = -13397,
            LED3G = -13396,
            LED3R = -13381,
            LED1G = -9077,
            LED1R = -9056,
            LED1B = -9040,
            LED = -8668,
            LED4B = 6862,
            LED4G = 6867,
            LED4R = 6910,
            LED5R = 13374,
            LED5G = 13381,
            LED5B = 13390,
            LED0G = 13697,
            LED0B = 13700,
            LED6B = 20051,
            LED6G = 20054,
            LED6R = 20067,
            LEDB = 21171,
            LED9R = 21508,
            LED9B = 21524,
            LED9G = 21535,
            LED0 = 30768,
            LED8G = 32738,
            LED8B = 32743,
            LED8R = 32759,
        }
    }
}
